# Generated by Django 5.0.1 on 2024-02-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('date', models.DateField()),
            ],
        ),
    ]
