# Generated by Django 5.0.1 on 2024-02-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
