# Generated by Django 5.0.1 on 2024-02-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0002_alter_flower_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='url',
            field=models.ImageField(blank=True, default='', upload_to='flowers/'),
        ),
    ]
